spring:
  application:
    name: AA-COMMAND
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 7093160053@kK
    url: jdbc:mysql://localhost:3306/practice
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-group